import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Activity } from "lucide-react";

/**
 * Lightweight, keyboard-navigable pitch deck for the hackathon judging panel.
 * Open at `/pitch`. Use ← → keys or on-screen controls. Designed for full-
 * screen screen-recording → drop into the submission video.
 */

const SLIDES = [
  {
    kicker: "ET AI HACKATHON 2026 · PHASE 2",
    title: ["Two agents.", <span key="2" className="block">Three million lungs.</span>, <span key="3" className="block text-white/40">One Delhi.</span>],
    sub: "AeroSentinel — turning ward-level air-quality signals into evidence-linked enforcement actions, in under six hours from signal to dispatch.",
  },
  {
    kicker: "PROBLEM",
    title: ["1.67M deaths.", <span key="d" className="block text-white/40">31% of cities can act on the data.</span>],
    sub: "900+ CAAQMS stations exist under NCAP. A 2024 CAG audit found only 31% of cities have any actionable multi-agency response protocol linked to the readings. The data exists. The intelligence layer to act on it does not.",
  },
  {
    kicker: "SCOPE — LOCKED",
    title: "Two cores. One demo layer.",
    sub: "We did not build all five illustrative components. A two-person team that spans five hard problems ships five shallow demos. We chose two technical cores that survive a judge's follow-up question, plus one demo layer that bolts on cheaply.",
    bullets: [
      "IN — Hyperlocal Predictive AQI Forecasting Agent",
      "IN — Enforcement Intelligence & Prioritisation Agent",
      "IN — Citizen Health Risk Advisory (demo layer)",
      "OUT — Geospatial Source Attribution (no ground-truth emission inventory)",
      "OUT — Multi-City Comparative Dashboard (visualisation, not an AI problem)",
    ],
  },
  {
    kicker: "CORE 1 · FORECASTING AGENT",
    title: ["RMSE ", <span key="r" className="text-[#EAB308]">10.4</span>, " vs ", <span key="p" className="text-white/40">14.2</span>, " baseline."],
    sub: "Ward-level 24/48/72-hour AQI forecast across 14 Delhi wards, blending diurnal + weekly seasonal profile with persistence. Measured against a persistence baseline — the explicit metric the brief names — we beat it by 26.8% on the held-out window.",
    bullets: [
      "14 wards · 24, 48, 72 hour horizons",
      "City avg model RMSE 10.4 · persistence 14.2 · −26.8%",
      "Every chart shows the model line AND the persistence baseline AND the held-out actual — judges can verify",
    ],
  },
  {
    kicker: "CORE 2 · ENFORCEMENT AGENT",
    title: ["48h → ", <span key="r" className="text-[#22C55E]">5.4h</span>, " signal-to-intervention."],
    sub: "Hotspots are correlated with a four-category registry (construction permits, industrial stacks, waste-burning zones, diesel fleet routes) to produce a ranked P1/P2/P3 queue. Every recommendation is traceable to the registry entries that produced it — judges can audit the trace.",
    bullets: [
      "13 prioritised P1/P2/P3 recommendations",
      "Each row expandable: hotspot AQI + correlated registry IDs",
      "One click = dispatch to field officer with ETA",
    ],
  },
  {
    kicker: "DEMO LAYER · CITIZEN ADVISORY",
    title: ["English ↔ ", <span key="h" className="font-hi text-[#EAB308]">हिन्दी</span>], 
    sub: "Bilingual ward-level health advisories generated by Gemini 3 Flash, cached per ward, with a deterministic fallback if the LLM is unreachable. Calm, practical, public-health tone — not alarmist.",
    bullets: [
      "Gemini 3 Flash via Emergent Universal Key",
      "Devanagari rendering with Noto Sans Devanagari",
      "Fallback advisory ensures zero-downtime UX",
    ],
  },
  {
    kicker: "DISCLOSED METHODOLOGY",
    title: "Synthetic-but-realistic. Stated upfront.",
    sub: "AQI station readings, the four-category registry, and the signal-to-intervention baseline are seeded synthetic data. Disclosed assumptions are a credibility asset; hidden ones are a liability. The pipeline accepts drop-in CPCB / CAAQMS / OpenAQ feeds via a single env var.",
    bullets: [
      "Set OPENAQ_API_KEY in backend/.env → live blend mode",
      "MongoDB persists enforcement state across restarts",
      "Demo \"now\" frozen to 2026-02-12 for reproducibility",
    ],
  },
  {
    kicker: "JUDGING CRITERIA · MAPPED",
    title: "Every weight, addressed.",
    bullets: [
      "Innovation (15%) — ward-level, not city-average; two agents that talk to each other",
      "Business Impact (25%) — explicit 48h → 5.4h dispatch latency reduction",
      "Technical Excellence (25%) — model RMSE 10.4 vs persistence 14.2, verifiable",
      "Scalability (20%) — port to a 2nd city = swap DELHI_WARDS array + drop-in OpenAQ feed",
      "User Experience (15%) — bilingual advisory, mission-control dark UI, one-click dispatch",
    ],
  },
  {
    kicker: "ROADMAP",
    title: "What's next.",
    bullets: [
      "Wire real CPCB / OpenAQ feeds for the historical trace (Week 5)",
      "Mumbai port — second city to prove portability claim (Week 6)",
      "Marathi, Tamil advisory languages",
      "Field-dispatch PDF export with QR-coded evidence trace",
      "WhatsApp Business push for citizen advisories",
    ],
  },
  {
    kicker: "TEAM",
    title: "Two people. Four weeks.",
    sub: "Person A: data pipeline + forecasting + RMSE benchmark + architecture diagram. Person B: enforcement engine + frontend + multilingual advisory + pitch narrative + demo video. Scope was locked in Week 1 and held to.",
  },
];

export default function Pitch() {
  const [i, setI] = useState(0);
  useEffect(() => {
    const handler = (e) => {
      if (e.key === "ArrowRight" || e.key === " ") setI((x) => Math.min(SLIDES.length - 1, x + 1));
      if (e.key === "ArrowLeft") setI((x) => Math.max(0, x - 1));
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, []);
  const s = SLIDES[i];
  return (
    <div data-testid="pitch-deck" className="min-h-screen bg-[#0A0A0A] text-white flex flex-col">
      <div className="border-b border-white/10 px-8 py-4 flex items-center justify-between">
        <Link to="/" className="flex items-center gap-2 text-white/60 hover:text-white text-xs font-mono-data uppercase tracking-wider">
          <Activity className="w-4 h-4" />
          AeroSentinel · back to dashboard
        </Link>
        <div className="font-mono-data text-xs text-white/40 tabular">
          {String(i + 1).padStart(2, "0")} / {String(SLIDES.length).padStart(2, "0")}
        </div>
      </div>

      <main className="flex-1 flex items-center justify-center px-8 lg:px-24 py-12">
        <div className="max-w-5xl w-full" key={i}>
          <div className="font-mono-data text-[10px] uppercase tracking-[0.3em] text-[#EAB308] mb-8 feed-in">
            {s.kicker}
          </div>
          <h1 className="font-display text-5xl md:text-7xl font-bold tracking-tighter leading-[0.95] mb-8 feed-in" style={{ animationDelay: "60ms" }}>
            {Array.isArray(s.title) ? s.title : s.title}
          </h1>
          {s.sub && (
            <p className="text-base md:text-lg text-white/60 leading-relaxed max-w-3xl mb-8 feed-in" style={{ animationDelay: "120ms" }}>
              {s.sub}
            </p>
          )}
          {s.bullets && (
            <ul className="space-y-3 max-w-3xl">
              {s.bullets.map((b, idx) => (
                <li
                  key={idx}
                  className="flex items-start gap-3 text-sm md:text-base text-white/80 leading-relaxed feed-in"
                  style={{ animationDelay: `${180 + idx * 60}ms` }}
                >
                  <span className="font-mono-data text-[#EAB308] mt-0.5 flex-shrink-0">
                    {String(idx + 1).padStart(2, "0")} ·
                  </span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
      </main>

      <div className="border-t border-white/10 px-8 py-4 flex items-center justify-between font-mono-data text-xs">
        <button
          data-testid="pitch-prev"
          onClick={() => setI((x) => Math.max(0, x - 1))}
          disabled={i === 0}
          className="flex items-center gap-2 px-4 py-2 border border-white/10 rounded-sm hover:border-white/30 disabled:opacity-30 disabled:cursor-not-allowed"
        >
          <ArrowLeft className="w-3.5 h-3.5" /> PREV
        </button>
        <div className="flex items-center gap-1">
          {SLIDES.map((_, idx) => (
            <button
              key={idx}
              data-testid={`pitch-dot-${idx}`}
              onClick={() => setI(idx)}
              className={`h-1 transition-all ${idx === i ? "w-8 bg-[#EAB308]" : "w-3 bg-white/20 hover:bg-white/40"}`}
              aria-label={`Go to slide ${idx + 1}`}
            />
          ))}
        </div>
        <button
          data-testid="pitch-next"
          onClick={() => setI((x) => Math.min(SLIDES.length - 1, x + 1))}
          disabled={i === SLIDES.length - 1}
          className="flex items-center gap-2 px-4 py-2 bg-white text-black rounded-sm hover:bg-[#22C55E] disabled:opacity-30 disabled:cursor-not-allowed"
        >
          NEXT <ArrowRight className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
}
